const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Seeding database...');

  // Create badges
  const badges = await Promise.all([
    prisma.badge.create({
      data: {
        name: 'First Steps',
        description: 'Complete your first environmental challenge',
        icon: '🌱',
        points: 10,
        category: 'ACHIEVEMENT'
      }
    }),
    prisma.badge.create({
      data: {
        name: 'Tree Hugger',
        description: 'Plant 5 trees',
        icon: '🌳',
        points: 50,
        category: 'CHALLENGE'
      }
    }),
    prisma.badge.create({
      data: {
        name: 'Waste Warrior',
        description: 'Complete 10 waste management challenges',
        icon: '♻️',
        points: 100,
        category: 'CHALLENGE'
      }
    }),
    prisma.badge.create({
      data: {
        name: 'Energy Saver',
        description: 'Complete 5 energy conservation challenges',
        icon: '⚡',
        points: 75,
        category: 'CHALLENGE'
      }
    }),
    prisma.badge.create({
      data: {
        name: 'Water Guardian',
        description: 'Complete 5 water conservation challenges',
        icon: '💧',
        points: 75,
        category: 'CHALLENGE'
      }
    }),
    prisma.badge.create({
      data: {
        name: 'Community Helper',
        description: 'Participate in 3 community challenges',
        icon: '🤝',
        points: 150,
        category: 'COMMUNITY'
      }
    }),
    prisma.badge.create({
      data: {
        name: 'Knowledge Seeker',
        description: 'Complete 10 learning modules',
        icon: '📚',
        points: 200,
        category: 'LEARNING'
      }
    }),
    prisma.badge.create({
      data: {
        name: 'Eco Champion',
        description: 'Reach level 10',
        icon: '🏆',
        points: 1000,
        category: 'ACHIEVEMENT'
      }
    })
  ]);

  console.log(`✅ Created ${badges.length} badges`);

  // Create sample users
  const users = await Promise.all([
    prisma.user.create({
      data: {
        email: 'admin@greened.com',
        password: '$2a$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewdBPj4J/8.5.5.5', // password123
        firstName: 'Admin',
        lastName: 'User',
        role: 'ADMIN',
        school: 'GreenEd Platform',
        points: 1000,
        level: 10
      }
    }),
    prisma.user.create({
      data: {
        email: 'teacher@greened.com',
        password: '$2a$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewdBPj4J/8.5.5.5', // password123
        firstName: 'Eco',
        lastName: 'Teacher',
        role: 'TEACHER',
        school: 'Punjab Public School',
        points: 500,
        level: 5
      }
    }),
    prisma.user.create({
      data: {
        email: 'student@greened.com',
        password: '$2a$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewdBPj4J/8.5.5.5', // password123
        firstName: 'Green',
        lastName: 'Student',
        role: 'STUDENT',
        school: 'Punjab Public School',
        grade: '10th',
        points: 150,
        level: 2
      }
    })
  ]);

  console.log(`✅ Created ${users.length} users`);

  // Create learning modules
  const modules = await Promise.all([
    prisma.module.create({
      data: {
        title: 'Introduction to Climate Change',
        description: 'Learn the basics of climate change and its impact on our planet',
        content: `
# Introduction to Climate Change

Climate change refers to long-term shifts in global temperatures and weather patterns. While climate variations are natural, since the 1800s human activities have been the main driver of climate change, primarily due to burning fossil fuels like coal, oil, and gas.

## Key Concepts

### Greenhouse Effect
The greenhouse effect is a natural process that warms the Earth's surface. When the Sun's energy reaches the Earth's atmosphere, some of it is reflected back to space and the rest is absorbed and re-radiated by greenhouse gases.

### Global Warming
Global warming is the long-term heating of Earth's climate system observed since the pre-industrial period due to human activities, primarily fossil fuel burning, which increases heat-trapping greenhouse gas levels in Earth's atmosphere.

### Carbon Footprint
A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions.

## Impact on Punjab

In Punjab, climate change is affecting:
- Agricultural productivity
- Water availability
- Temperature patterns
- Monsoon variability

## What You Can Do

1. Reduce energy consumption
2. Use renewable energy sources
3. Plant trees
4. Reduce waste
5. Conserve water
        `,
        category: 'CLIMATE_CHANGE',
        difficulty: 'EASY',
        points: 50,
        duration: 30
      }
    }),
    prisma.module.create({
      data: {
        title: 'Renewable Energy Sources',
        description: 'Explore different types of renewable energy and their benefits',
        content: `
# Renewable Energy Sources

Renewable energy is energy from sources that are naturally replenishing but flow-limited. Renewable resources are virtually inexhaustible in duration but limited in the amount of energy that is available per unit of time.

## Types of Renewable Energy

### Solar Energy
Solar energy is radiant light and heat from the Sun that is harnessed using a range of technologies such as solar heating, photovoltaics, and solar thermal energy.

### Wind Energy
Wind energy is the use of air flow through wind turbines to mechanically power generators for electricity.

### Hydroelectric Power
Hydroelectric power is electricity produced from generators driven by turbines that convert the potential energy of falling or fast-flowing water into mechanical energy.

### Biomass Energy
Biomass energy is energy derived from organic matter, such as plants, wood, and waste.

## Benefits

- Reduces greenhouse gas emissions
- Creates jobs
- Improves air quality
- Reduces dependence on fossil fuels
- Provides energy security

## Implementation in Punjab

Punjab has great potential for:
- Solar energy (abundant sunlight)
- Biomass energy (agricultural waste)
- Small hydro projects
        `,
        category: 'RENEWABLE_ENERGY',
        difficulty: 'MEDIUM',
        points: 75,
        duration: 45
      }
    }),
    prisma.module.create({
      data: {
        title: 'Waste Management and Recycling',
        description: 'Learn about proper waste segregation and recycling practices',
        content: `
# Waste Management and Recycling

Waste management is the collection, transport, processing, and disposal of waste materials. Proper waste management is crucial for environmental protection and public health.

## Types of Waste

### Biodegradable Waste
- Food scraps
- Garden waste
- Paper products
- Wood

### Non-biodegradable Waste
- Plastic
- Metal
- Glass
- Electronic waste

## The 3 R's

### Reduce
- Buy only what you need
- Choose products with less packaging
- Use reusable items

### Reuse
- Donate items in good condition
- Repurpose containers
- Repair instead of replacing

### Recycle
- Separate recyclable materials
- Use recycling facilities
- Buy products made from recycled materials

## Waste Segregation

### Green Bin (Biodegradable)
- Food waste
- Garden waste
- Paper towels

### Blue Bin (Recyclable)
- Paper and cardboard
- Plastic bottles
- Metal cans
- Glass bottles

### Red Bin (Non-recyclable)
- Plastic bags
- Styrofoam
- Broken glass
- Hazardous waste

## Composting

Composting is the natural process of recycling organic matter into a rich soil amendment called compost.

### Benefits
- Reduces waste
- Creates nutrient-rich soil
- Reduces need for chemical fertilizers
- Improves soil structure
        `,
        category: 'WASTE_MANAGEMENT',
        difficulty: 'EASY',
        points: 60,
        duration: 35
      }
    })
  ]);

  console.log(`✅ Created ${modules.length} modules`);

  // Create quizzes for modules
  const quizzes = await Promise.all([
    // Climate Change Module Quizzes
    prisma.quiz.create({
      data: {
        moduleId: modules[0].id,
        question: 'What is the main cause of climate change in recent decades?',
        options: JSON.stringify([
          'Natural climate variations',
          'Human activities, especially burning fossil fuels',
          'Solar radiation changes',
          'Volcanic eruptions'
        ]),
        correct: 1,
        points: 10
      }
    }),
    prisma.quiz.create({
      data: {
        moduleId: modules[0].id,
        question: 'What is a carbon footprint?',
        options: JSON.stringify([
          'The size of your foot',
          'The total amount of greenhouse gases generated by your actions',
          'The amount of carbon in the soil',
          'The height of carbon dioxide in the atmosphere'
        ]),
        correct: 1,
        points: 10
      }
    }),
    // Renewable Energy Module Quizzes
    prisma.quiz.create({
      data: {
        moduleId: modules[1].id,
        question: 'Which renewable energy source is most suitable for Punjab?',
        options: JSON.stringify([
          'Wind energy',
          'Solar energy',
          'Geothermal energy',
          'Tidal energy'
        ]),
        correct: 1,
        points: 15
      }
    }),
    // Waste Management Module Quizzes
    prisma.quiz.create({
      data: {
        moduleId: modules[2].id,
        question: 'Which bin should food waste go into?',
        options: JSON.stringify([
          'Blue bin (recyclable)',
          'Green bin (biodegradable)',
          'Red bin (non-recyclable)',
          'Yellow bin (hazardous)'
        ]),
        correct: 1,
        points: 10
      }
    })
  ]);

  console.log(`✅ Created ${quizzes.length} quizzes`);

  // Create challenges
  const challenges = await Promise.all([
    prisma.challenge.create({
      data: {
        title: 'Plant a Tree',
        description: 'Plant a tree in your school, home, or community and document the process',
        category: 'TREE_PLANTING',
        difficulty: 'EASY',
        type: 'TASK',
        points: 100,
        requirements: JSON.stringify({
          instructions: [
            'Choose a suitable location for planting',
            'Select an appropriate tree species for your area',
            'Dig a hole twice the size of the root ball',
            'Plant the tree and water it thoroughly',
            'Take a photo of the planted tree',
            'Write a brief description of the planting process'
          ],
          materials: ['Tree sapling', 'Shovel', 'Water', 'Mulch (optional)'],
          duration: '1-2 hours'
        }),
        createdBy: users[1].id // Teacher
      }
    }),
    prisma.challenge.create({
      data: {
        title: 'Waste Segregation Setup',
        description: 'Set up a waste segregation system at home or school',
        category: 'WASTE_SEGREGATION',
        difficulty: 'EASY',
        type: 'TASK',
        points: 75,
        requirements: JSON.stringify({
          instructions: [
            'Create separate bins for different types of waste',
            'Label each bin clearly',
            'Educate family members or classmates about proper segregation',
            'Document the setup with photos',
            'Maintain the system for at least one week'
          ],
          materials: ['Bins or containers', 'Labels', 'Markers'],
          duration: '2-3 hours setup, 1 week maintenance'
        }),
        createdBy: users[1].id // Teacher
      }
    }),
    prisma.challenge.create({
      data: {
        title: 'Energy Conservation Audit',
        description: 'Conduct an energy audit of your home or classroom',
        category: 'ENERGY_CONSERVATION',
        difficulty: 'MEDIUM',
        type: 'PROJECT',
        points: 150,
        requirements: JSON.stringify({
          instructions: [
            'List all electrical appliances and devices',
            'Check for energy-efficient alternatives',
            'Identify areas of energy waste',
            'Create an action plan for energy conservation',
            'Implement at least 3 energy-saving measures',
            'Document the process and results'
          ],
          materials: ['Notebook', 'Camera', 'Energy meter (optional)'],
          duration: '1-2 weeks'
        }),
        createdBy: users[1].id // Teacher
      }
    }),
    prisma.challenge.create({
      data: {
        title: 'Community Cleanup Drive',
        description: 'Organize a cleanup drive in your neighborhood or school',
        category: 'CLEANUP_DRIVE',
        difficulty: 'HARD',
        type: 'COMMUNITY',
        points: 200,
        requirements: JSON.stringify({
          instructions: [
            'Identify a location that needs cleaning',
            'Get permission from local authorities if needed',
            'Gather volunteers (friends, family, classmates)',
            'Organize cleanup materials and safety equipment',
            'Conduct the cleanup drive',
            'Properly dispose of collected waste',
            'Document the before and after with photos'
          ],
          materials: ['Gloves', 'Trash bags', 'Brooms', 'Safety equipment'],
          duration: '1 day event, 1 week planning'
        }),
        createdBy: users[0].id // Admin
      }
    })
  ]);

  console.log(`✅ Created ${challenges.length} challenges`);

  // Create forum posts
  const forumPosts = await Promise.all([
    prisma.forumPost.create({
      data: {
        title: 'Welcome to GreenEd Platform!',
        content: 'Welcome everyone to our environmental education platform. Let\'s work together to make our planet greener and more sustainable!',
        category: 'ANNOUNCEMENTS',
        userId: users[0].id, // Admin
        isPinned: true
      }
    }),
    prisma.forumPost.create({
      data: {
        title: 'Best Practices for Tree Planting',
        content: 'Share your experiences and tips for successful tree planting. What species work best in your area?',
        category: 'GENERAL',
        userId: users[1].id // Teacher
      }
    }),
    prisma.forumPost.create({
      data: {
        title: 'My First Composting Experience',
        content: 'I started composting at home last month and it\'s amazing how much waste we can reduce! Anyone else trying composting?',
        category: 'SUCCESS_STORIES',
        userId: users[2].id // Student
      }
    })
  ]);

  console.log(`✅ Created ${forumPosts.length} forum posts`);

  // Create internships
  const internships = await Promise.all([
    prisma.internship.create({
      data: {
        title: 'Environmental Research Intern',
        description: 'Join our research team studying climate change impacts on local agriculture',
        company: 'Punjab Environmental Research Institute',
        location: 'Chandigarh, Punjab',
        type: 'FULL_TIME',
        duration: '3 months',
        requirements: 'Students pursuing Environmental Science, Biology, or related fields. Basic knowledge of data analysis preferred.',
        createdBy: users[0].id // Admin
      }
    }),
    prisma.internship.create({
      data: {
        title: 'Community Outreach Volunteer',
        description: 'Help organize environmental awareness programs in rural areas',
        company: 'Green Punjab Foundation',
        location: 'Various locations in Punjab',
        type: 'PART_TIME',
        duration: '2 months',
        requirements: 'Good communication skills, passion for environmental causes, ability to travel.',
        createdBy: users[1].id // Teacher
      }
    })
  ]);

  console.log(`✅ Created ${internships.length} internships`);

  // Award some badges to users
  await prisma.userBadge.create({
    data: {
      userId: users[2].id, // Student
      badgeId: badges[0].id // First Steps
    }
  });

  await prisma.userBadge.create({
    data: {
      userId: users[1].id, // Teacher
      badgeId: badges[6].id // Knowledge Seeker
    }
  });

  console.log('✅ Awarded sample badges');

  console.log('🎉 Database seeding completed successfully!');
}

main()
  .catch((e) => {
    console.error('❌ Seeding failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });